development:
  access_key_id: AKIAJTOLKLEDRZML6HRA
  secret_access_key: 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

production:
  access_key_id: AKIAJTOLKLEDRZML6HRA
  secret_access_key: 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