# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57ebefba849d418d02cd5fd3857191b47f2bbef539652f8329e76c57b5fb8d97ff13efbd33c56fec412dae019af3518b4143b67816ca01f2e73b7cb502dec4e7

test:
  secret_key_base: 52cf6ec98b8276d2a69efab493dacc1869834872a3108f4f50f01381bea2b6d640ca16fdac1a143f9eae925436d5d96a1ec7c23752c9fa7c3152cd5731d50082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
